# Generated by Django 5.1.7 on 2025-04-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('green', 'Green'), ('white', 'White'), ('blue', 'Blue')], max_length=10)),
                ('size', models.FloatField()),
                ('length', models.IntegerField(choices=[(50, '50 ft'), (100, '100 ft')])),
                ('weight', models.FloatField()),
                ('availability', models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold Out')], max_length=10)),
            ],
            options={
                'ordering': ['size'],
            },
        ),
    ]
