# Generated by Django 5.1.7 on 2025-04-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterField(
            model_name='item',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('sold out', 'Sold Out')], max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.IntegerField(choices=[(50, '50 ft.'), (100, '100 ft.')]),
        ),
    ]
