# Generated by Django 5.1.7 on 2025-04-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_options_alter_item_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.IntegerField(choices=[(125, '125gm'), (135, '135gm'), (150, '150gm'), (160, '160gm'), (170, '170gm'), (190, '190gm'), (200, '200gm'), (250, '250gm')], default=125),
        ),
        migrations.AlterField(
            model_name='item',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('sold out', 'Sold Out')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.IntegerField(choices=[(50, '50ft'), (100, '100ft')]),
        ),
    ]
