# Generated by Django 5.1.7 on 2025-04-02 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_category_alter_item_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='item',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
