# Generated by Django 5.1.7 on 2025-04-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='availability',
            field=models.CharField(choices=[('available', 'Available ✅'), ('sold out', 'Sold Out ❌')], max_length=20),
        ),
    ]
