# Generated by Django 5.1.7 on 2025-04-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_alter_item_date_added_alter_item_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('chura', 'Chura'), ('stitch/dhaga mat', 'Stitch/Dhaga Mat'), ('pure mat', 'Pure Mat')], default='chura', max_length=20),
        ),
    ]
