# Generated by Django 5.1.7 on 2025-04-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('chura', 'Chura'), ('stitch mat', 'Stitch Mat'), ('pure mat', 'Pure Mat')], default='chura', max_length=20),
        ),
    ]
