# Generated by Django 5.1.7 on 2025-04-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_item_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='FibreSheetJali',
        ),
    ]
