# Generated by Django 5.1.7 on 2025-04-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_rename_item_fibresheetjali'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fibresheetjali',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventory'},
        ),
    ]
