# Generated by Django 5.1.7 on 2025-04-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_alter_fibresheetjali_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fibresheetjali',
            options={},
        ),
    ]
