# Generated by Django 5.1.7 on 2025-04-05 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_alter_fibresheetjali_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FibreSheetCloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(choices=[('green', 'Green 🟩'), ('white', 'White ⬜'), ('blue', 'Blue 🟦')], max_length=10)),
                ('size', models.FloatField()),
                ('length', models.IntegerField(choices=[(50, '50ft'), (100, '100ft')])),
                ('weight', models.FloatField()),
                ('category', models.IntegerField(choices=[(125, '125gm'), (135, '135gm'), (150, '150gm'), (160, '160gm'), (170, '170gm'), (190, '190gm'), (200, '200gm'), (250, '250gm')], default=125)),
                ('type', models.CharField(choices=[('chura', 'Chura'), ('stitch mat', 'Stitch Mat'), ('pure mat', 'Pure Mat')], default='chura', max_length=20)),
                ('availability', models.CharField(choices=[('available', 'Available ✅'), ('sold out', 'Sold Out ❌')], max_length=20)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fibre Sheet Cloth',
                'verbose_name_plural': 'Fibre Sheet Cloth',
            },
        ),
    ]
