services:
  - type: web
    name: django-admin
    runtime: python
    buildCommand: "build.bat" # Changed to .bat
    startCommand: "gunicorn inventory_management.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DISABLE_COLLECTSTATIC
        value: 0
      - key: PYTHON_VERSION
        value: 3.9.13
